### ISSUE TITLE
Always return false when use api create?

### ISSUE THREAD

**Issue by sonhip94** [jwplayer/jwplatform-php#11]
![image](https://user-images.githubusercontent.com/30177470/68051274-9d810980-fd19-11e9-9ac1-1a7f12ef2d56.png)
Can you help me? i dont know why :( I running your example.

**Comment by ksindi** [comment]
Hi @sonhip94. For debugging questions, please ask in [stackoverflow](https://stackoverflow.com) and tag with jwplayer.
