### ISSUE TITLE
Message: Class 'Jwplayer\JwplatformAPI' not found

### ISSUE THREAD

**Issue by mvlorenzo** [jwplayer/jwplatform-php#12]
I'm getting an error Message: Class 'Jwplayer\JwplatformAPI' not found

**Comment by ksindi** [comment]
@mvlorenzo did you use composer or did you install manually? Also can you please share how you installed with `composer`?

**Comment by mvlorenzo** [comment]
> @mvlorenzo did you use composer or did you install manually? Also can you please share how you installed with `composer`?

I used composer, but when I used require it worked, now I have another problem I'm getting this error api_signature: Signature is invalid

**Comment by ksindi** [comment]
Thanks @mvlorenzo. Can you please elaborate what you mean by "when I used require it worked"? Did composer not work?

Check https://beta-developer.jwplayer.com/jwplayer/docs/manage-your-library-with-the-management-api#section-requirements to get the correct API credentials.

**Comment by ksindi** [comment]
Add `-o` fixes class not being found https://github.com/jwplayer/jwplatform-php/pull/14
