### ISSUE TITLE
protectionrules endpoint

### ISSUE THREAD

**Issue by enriquesomolinos** [jwplayer/jwplatform-php#18]
Hi we are starting to use your php api library in order to manage our video library.

We can upload, update, create, remove videos, thumbnails and more. But we cannot manage the protectionrules (geoblocking rules), we cannot show what protectionrules we have in the platform via API.

I see in the dashboard that there is a call https://api.jwplayer.com/botr/sites/xxxxxx/accounts/protectionrules/create

Can you integrate this kind of calls in this library?
Thanks.

**Comment by ksindi** [comment]
Hi @enriquesomolinos. Accessing protection rules isn't something we officially support at the moment. But it's in our roadmap.
