### ISSUE TITLE
Can't fetch list of players

### ISSUE THREAD

**Issue by dkirchhof** [jwplayer/jwplatform-php#29]
Hello,
I just wanted to check out this library but have problems while fetching players.

I use the following code to get a list of all players:
```php
$client = new JwplatformClient($apiSecret);
$result = $client->Player->list($siteId);

var_dump($result);
```
But I get the following error: "The requested resource could not be found."

If I replace "Player" with "Media" I can fetch all videos. So the secret and site id is correct.
I'm using version 2.0.0.

**Comment by dkirchhof** [comment]
https://github.com/jwplayer/jwplatform-php/pull/31

**Comment by polishmatt** [comment]
Resolved by PR.
