### ISSUE TITLE
API V2: Get Media doesn't work

### ISSUE THREAD

**Issue by bpshadow** [jwplayer/jwplatform-php#40]
When I try to get the media by site and ID, I get this error.
```
{"errors": [{"code": "method_not_allowed", "description": "The provided method is not allowed on the targeted resource."}]}
```

According to the doc, it should use the GET method.
https://docs.jwplayer.com/platform/reference/get_v2-sites-site-id-media-media-id

But the code is using the POST method.
https://github.com/jwplayer/jwplatform-php/blob/master/src/JwplatformAPI.php#L199-L200

**Comment by polishmatt** [comment]
Use JwplatformClient instead of JwplatformAPI with the V2 API. The V2 support added in JwplatformAPI was only a partial implementation.
